### ISSUE TITLE
Bower task in Azure VSTS(VSO/TFS) is using outdated/incorrect version/registry url

### ISSUE THREAD

**Issue by coreyzw** [touchifyapp/vsts-bower#5]
Bower task for VSTS builds are returning a 410 error:
"EINVRES Request to https://bower.herokuapp.com/packages/bootstrap-validator failed with 410"

**Comment by chris-evolve** [comment]
I am getting the same error - first experienced 18th October:
bower angular#1.5.8            EINVRES Request to https://bower.herokuapp.com/packages/angular failed with 410
using hosted VS2017 build agent.

**Comment by chris-evolve** [comment]
I was investigating the possibility I needed to perform an npm install, but noticed just now that I no longer get the build task install error.

Has anything changed?

**Comment by SomaticIT** [comment]
I'm not sure this issue is directly related to this project.
You should explain this issue to the bower team (which is not really active this times...).

This task does not embed any version of Bower. It's a simple wrapper around the NPM Bower CLI.
It install the package during it's first execution if it's not installed.
You can install, update or manage the Bower version you prefer manually on your agent.
